---
- name: main / Load service variables
  include_vars: roles/haproxy/vars/{{ cluster_service }}.yml
- import_tasks: tasks/haproxy_check_install.yml
- import_tasks: tasks/haproxy_install.yml
- import_tasks: tasks/haproxy_configure.yml
...
