---
## Wordpressのデプロイ
- name: install / Download Wordpress
  git:
    repo: https://github.com/WordPress/WordPress
    dest: "/home/ec2-user/wordpress-{{ wordpress_version }}"
    version: "{{ wordpress_version }}-branch"

## ドキュメントルートの作成
- name: install / Create link wordpress root document
  file:
    src: /home/ec2-user/wordpress-{{ wordpress_version }}
    path: /var/www/html/wordpress
    owner: apache
    group: apache
    state: link

## 所有者とパーミッション変更
- name: install / wordpress directory Permission change
  file:
    path: /home/ec2-user/wordpress-{{ wordpress_version }}
    owner: apache
    group: apache
    mode: 0755
    recurse: yes

## ユーザのホームディレクトリのパーミッション変更
## useraddで追加した状態は700なので、755にしないとシンボリックリンクから辿れない。
- name: install / user direcotory Permission change
  file:
    path: /home/{{ user_dir }}
    mode: 0755
...
