---
- name: td-agent install check
  yum:
    list: td-agent
  register: yum_check

- name: fluentd-plugin existence check
  find:
    paths: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems
    recurse: no
    file_type: directory
    patterns: 'fluent-plugin-multiprocess*'
  register: plugin_check

- name: add repository & install td
  shell: curl -L https://toolbelt.treasuredata.com/sh/install-redhat-td-agent3.sh | sh
  when:  yum_check.results | selectattr("yumstate", "match", "installed") | list | length == 0

- name: install plugin for td_agent
  gem:
    executable: /usr/sbin/td-agent-gem
    name: fluent-plugin-multiprocess
    state: latest
    user_install: no
#    version: 1.0.0
  when: plugin_check.matched == 0
...
