---
network_kernel_parameters:
  - name: net.core.somaxconn
    value: "1024"
  - name: net.core.netdev_max_backlog
    value: "5000"
  - name: net.core.rmem_max
    value: "16777216"
  - name: net.core.wmem_max
    value: "16777216"
  - name: net.ipv4.tcp_wmem
    value: "4096 12582912 16777216"
  - name: net.ipv4.tcp_rmem
    value: "4096 12582912 16777216"
  - name: net.ipv4.tcp_max_syn_backlog
    value: "8096"
  - name: net.ipv4.tcp_slow_start_after_idle
    value: "0"
  - name: net.ipv4.tcp_tw_reuse
    value: "1"
  - name: net.ipv4.ip_local_port_range
    value: "10240 65535"

td_server_plugin:
  - { name: 'fluent-plugin-multiprocess', version: '' }
  - { name: 'fluent-plugin-multi-format-parser', version: '' }
  - { name: 'fluent-plugin-elasticsearch', version: '' }
  - { name: 'fluent-plugin-file-alternative', version: '' }
  - { name: 'fluent-plugin-forest', version: '' }
  - { name: 'fluent-plugin-s3', version: '' }
  - { name: 'fluent-plugin-flowcounter', version: '' }

td_log_dir:
  - /var/log/fluentd
  - /var/log/td-agent/pos
...
