---
## ホスト名の設定
- name: main / Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

## NetoworkManagerのリゾルバ設定
- name: main / Set resolver setting
  ini_file:
    dest: /etc/NetworkManager/NetworkManager.conf
    section: main
    option: dns
    value: no

## ネームサービススイッチの設定
- name: main / Deploy nsswitch.conf
  copy:
    src: nsswitch.conf
    dest: /etc/nsswitch.conf
    owner: root
    group: root
    mode: 0644

## resolv.confの設定
- name: main / Deploy resolv.conf
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644

## hostsファイルの設定
- name: main / Deploy hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
