---
## deploy config file
- name: elasticsearch.yml setting
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660

- name: elasticsearch service start
  systemd:
    name: elasticsearch
    enabled: yes
    state: restarted
# - name: jvm.options setting
#   template:
#     src: jvm.options.j2
#     dest: /etc/elasticsearch/jvm.options
#     owner: root
#     group: root
#     mode: 0660
#   notify: restart_elasticsearch
